In [1]:
from azureml.core.experiment import Experiment
from azureml.core.workspace import Workspace
from azureml.train.automl import AutoMLConfig
from azureml.core.dataset import Dataset

In [3]:
print('SDK Version is:', azureml.core.VERSION)

SDK Version is: 1.19.0

In [6]:
ws = Workspace.from_config()
print(ws.name, ws.location, ws.resource_group, ws.subscription_id, sep= "\n")

quick-starts-ws-134433
southcentralus
aml-quickstarts-134433
aa7cf8e8-d23f-4bce-a7b9-1f0b4e0ac8ee

In [7]:
experiment_name = "automl-exp"
project_folder = "./automl-project"

exp = Experiment(ws, experiment_name)
exp

Experiment(Name: automl-exp,
Workspace: quick-starts-ws-134433)

In [9]:
from azureml.core.compute import ComputeTarget
from azureml.core.compute_target import ComputeTargetException
from azureml.core.compute import AmlCompute

cluster_name= "AML-Cluster"

#Verify that cluster does not exist already
try:
    compute_target = ComputeTarget(workspace=ws, name=cluster_name)
    print('Found existing cluster, use it.')
    
except ComputeTargetException:
    compute_config = AmlCompute.provisioning_configuration(vm_size='STANDARD_DS12_v2',
                                                           min_nodes=1, max_nodes=5)
    
    compute_target = ComputeTarget.create(ws, cluster_name, compute_config)

compute_target.wait_for_completion(show_output=True, min_node_count = 1, timeout_in_minutes = 10)
compute_target.get_status()

Creating
Succeeded........................
AmlCompute wait for completion finished

Minimum number of nodes requested have been provisioned

In [10]:
#loading the data
found = False
key = "BankMarketing Dataset"
description_text = "Bank-Marketing Dataset for Project"

if key in ws.datasets.keys(): 
        found = True
        dataset = ws.datasets[key] 

if not found:
        # Create AML Dataset and register it into Workspace
        data = 'https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/bankmarketing_train.csv'
        dataset = Dataset.Tabular.from_delimited_files(data)        
        #Register Dataset in Workspace
        dataset = dataset.register(workspace=ws,
                                   name=key,
                                   description=description_text)


df = dataset.to_pandas_dataframe()

In [11]:
#view the data
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,57,technician,married,high.school,no,no,yes,cellular,may,mon,...,1,999,1,failure,-1.8,92.893,-46.2,1.299,5099.1,no
1,55,unknown,married,unknown,unknown,yes,no,telephone,may,thu,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191.0,no
2,33,blue-collar,married,basic.9y,no,no,no,cellular,may,fri,...,1,999,1,failure,-1.8,92.893,-46.2,1.313,5099.1,no
3,36,admin.,married,high.school,no,no,no,telephone,jun,fri,...,4,999,0,nonexistent,1.4,94.465,-41.8,4.967,5228.1,no
4,27,housemaid,married,high.school,no,yes,no,cellular,jul,fri,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,no

In [12]:
df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000
mean,40.040212,257.335205,2.561730,962.174780,0.174780,0.076228,93.574243,-40.518680,3.615654,5166.859608
std,10.432313,257.331700,2.763646,187.646785,0.496503,1.572242,0.578636,4.623004,1.735748,72.208448
min,17.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.000000,179.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.000000,318.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [13]:
automl_settings = {
    "experiment_timeout_minutes": 30,
    "max_concurrent_iterations": 3,
    "primary_metric" : 'AUC_weighted'
}
automl_config = AutoMLConfig(compute_target=compute_target,
                             task = "classification",
                             training_data=dataset,
                             label_column_name="y",   
                             path = project_folder,
                             enable_early_stopping= True,
                             featurization= 'auto',
                             enable_onnx_compatible_models=True,
                             debug_log = "automl_errors.log",
                             **automl_settings
                            )

In [14]:
# Submit automl run
automl_run = exp.submit(automl_config, show_output=True)

Running on remote.
No run_configuration provided, running on AML-Cluster with default configuration
Running on remote compute: AML-Cluster
Parent Run ID: AutoML_5190fa9d-1bbc-430d-a133-e77f622d4bba

Current status: FeaturesGeneration. Generating features for the dataset.
Current status: DatasetBalancing. Beginning model selection.
Current status: ModelSelection. Beginning model selection.

****************************************************************************************************
DATA GUARDRAILS:

TYPE:         Train-Test data split
STATUS:       DONE
DESCRIPTION:  Your input data has been split into a training dataset and a holdout test dataset for validation of the model. The test holdout dataset reflects the original distribution of your input data.

DETAILS:
+---------------------------------+---------------------------------+---------------------------------+
|Dataset                          |Row counts                       |Percentage                       |
+=================================+=================================+=================================+
|train                            |29655                            |90.0                             |
|test                             |3295                             |10.0                             |
+---------------------------------+---------------------------------+---------------------------------+

****************************************************************************************************

TYPE:         Class balancing detection
STATUS:       ALERTED
DESCRIPTION:  To decrease model bias, please cancel the current run and fix balancing problem.
              Learn more about imbalanced data: https://aka.ms/AutomatedMLImbalancedData
DETAILS:      Imbalanced data can lead to a falsely perceived positive effect of a model's accuracy because the input data has bias towards one class.
+---------------------------------+---------------------------------+--------------------------------------+
|Size of the smallest class       |Name/Label of the smallest class |Number of samples in the training data|
+=================================+=================================+======================================+
|3323                             |yes                              |29655                                 |
+---------------------------------+---------------------------------+--------------------------------------+

****************************************************************************************************

TYPE:         High cardinality feature detection
STATUS:       PASSED
DESCRIPTION:  Your inputs were analyzed, and no high cardinality features were detected.
              Learn more about high cardinality feature handling: https://aka.ms/AutomatedMLFeaturization

****************************************************************************************************

****************************************************************************************************
ITERATION: The iteration being evaluated.
PIPELINE: A summary description of the pipeline being evaluated.
DURATION: Time taken for the current iteration.
METRIC: The result of computing score on the fitted pipeline.
BEST: The best observed score thus far.
****************************************************************************************************

 ITERATION   PIPELINE                                       DURATION      METRIC      BEST
         1   MaxAbsScaler XGBoostClassifier                 0:00:48       0.9392    0.9392
         0   MaxAbsScaler LightGBM                          0:00:51       0.9450    0.9450
         2   MaxAbsScaler RandomForest                      0:00:45       0.8982    0.9450
         3   MaxAbsScaler RandomForest                      0:02:05       0.9017    0.9450
         4   MaxAbsScaler RandomForest                      0:02:01       0.9046    0.9450
         5   MaxAbsScaler ExtremeRandomTrees                0:01:10       0.9035    0.9450
         6   MaxAbsScaler ExtremeRandomTrees                0:00:39       0.8793    0.9450
         7   MaxAbsScaler ExtremeRandomTrees                0:00:42       0.8444    0.9450
         8   MaxAbsScaler RandomForest                      0:00:48       0.8925    0.9450
         9   MaxAbsScaler ExtremeRandomTrees                0:00:43       0.8239    0.9450
        10   MaxAbsScaler RandomForest                      0:00:37       0.9124    0.9450
        11   MaxAbsScaler RandomForest                      0:00:42       0.8821    0.9450
        12   MaxAbsScaler RandomForest                      0:00:48       0.8720    0.9450
        13   StandardScalerWrapper XGBoostClassifier        0:00:45       0.9309    0.9450
        14   MaxAbsScaler RandomForest                      0:00:41       0.9033    0.9450
        15   StandardScalerWrapper ExtremeRandomTrees       0:00:42       0.8858    0.9450
        16   MaxAbsScaler ExtremeRandomTrees                0:00:47       0.7976    0.9450
        17   MaxAbsScaler ExtremeRandomTrees                0:00:44       0.8057    0.9450
        18   MaxAbsScaler RandomForest                      0:00:49       0.8686    0.9450
        19   MaxAbsScaler LightGBM                          0:00:38       0.9404    0.9450
        20   MaxAbsScaler LightGBM                          0:00:44       0.9305    0.9450
        22   MaxAbsScaler LightGBM                          0:00:40       0.9212    0.9450
        21   StandardScalerWrapper XGBoostClassifier        0:00:59       0.9441    0.9450
        23   StandardScalerWrapper XGBoostClassifier        0:00:48       0.9432    0.9450
        24   StandardScalerWrapper XGBoostClassifier        0:01:04       0.9446    0.9450
        25   TruncatedSVDWrapper LightGBM                   0:00:46       0.9080    0.9450
        26   TruncatedSVDWrapper XGBoostClassifier          0:01:01       0.9354    0.9450
        28   StandardScalerWrapper XGBoostClassifier        0:00:48       0.9337    0.9450
        29   StandardScalerWrapper XGBoostClassifier        0:00:39       0.9289    0.9450
        27   StandardScalerWrapper XGBoostClassifier        0:01:20       0.9443    0.9450
        30   MaxAbsScaler LightGBM                          0:01:10       0.9395    0.9450
        31   MaxAbsScaler DecisionTree                      0:00:45       0.9234    0.9450
        32   MaxAbsScaler LightGBM                          0:00:45       0.9448    0.9450
        33                                                  0:00:16          nan    0.9450
        34    VotingEnsemble                                0:01:35       0.9480    0.9480